"""add_company_hr_payroll_tables

Revision ID: b34900117ba2
Revises: 8ad213f86345
Create Date: 2026-09-17 10:06:52.122089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b34900117ba2'
down_revision: Union[str, Sequence[str], None] = '8ad213f86345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='0->inactive, 1->active'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('status IN (0, 1)', name='chk_departments_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_departments_tenant_code')
    )
    op.create_index('idx_departments_tenant_status', 'departments', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_departments_tenant_id'), 'departments', ['tenant_id'], unique=False)
    op.create_table('designations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False, comment='1->staff, 2->senior, 3->lead, 4->manager, 5->director, 6->c_level'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('level BETWEEN 1 AND 6', name='chk_designations_level'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_designations_tenant_dept', 'designations', ['tenant_id', 'department_id'], unique=False)
    op.create_index(op.f('ix_designations_department_id'), 'designations', ['department_id'], unique=False)
    op.create_index(op.f('ix_designations_tenant_id'), 'designations', ['tenant_id'], unique=False)
    op.create_table('employees',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('designation_id', sa.UUID(), nullable=True),
    sa.Column('nik', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=False, comment='0->unspecified, 1->male, 2->female'),
    sa.Column('employment_type', sa.SmallInteger(), nullable=False, comment='1->permanent, 2->contract, 3->intern, 4->freelance'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='0->inactive, 1->active, 2->probation, 3->resigned, 4->terminated'),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('basic_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_account_holder', sa.String(length=150), nullable=True),
    sa.Column('npwp', sa.String(length=30), nullable=True),
    sa.Column('bpjs_tk_number', sa.String(length=30), nullable=True),
    sa.Column('bpjs_kes_number', sa.String(length=30), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('basic_salary >= 0', name='chk_employees_basic_salary'),
    sa.CheckConstraint('employment_type IN (1, 2, 3, 4)', name='chk_employees_employment_type'),
    sa.CheckConstraint('gender IN (0, 1, 2)', name='chk_employees_gender'),
    sa.CheckConstraint('status IN (0, 1, 2, 3, 4)', name='chk_employees_status'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nik', name='uq_employees_tenant_nik')
    )
    op.create_index('idx_employees_tenant_dept', 'employees', ['tenant_id', 'department_id'], unique=False)
    op.create_index('idx_employees_tenant_status', 'employees', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_designation_id'), 'employees', ['designation_id'], unique=False)
    op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('period_month', sa.SmallInteger(), nullable=False, comment='Bulan periode (1-12)'),
    sa.Column('period_year', sa.SmallInteger(), nullable=False, comment='Tahun periode (misal 2026)'),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_net', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='0->draft, 1->calculated, 2->approved, 3->paid, 4->void'),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_account_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('period_month BETWEEN 1 AND 12', name='chk_payroll_runs_month'),
    sa.CheckConstraint('period_year >= 2000', name='chk_payroll_runs_year'),
    sa.CheckConstraint('status IN (0, 1, 2, 3, 4)', name='chk_payroll_runs_status'),
    sa.CheckConstraint('total_gross >= 0 AND total_deductions >= 0 AND total_net >= 0', name='chk_payroll_runs_amounts'),
    sa.ForeignKeyConstraint(['payment_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'period_year', 'period_month', name='uq_payroll_runs_period')
    )
    op.create_index('idx_payroll_runs_status', 'payroll_runs', ['status'], unique=False)
    op.create_index('idx_payroll_runs_tenant_period', 'payroll_runs', ['tenant_id', 'period_year', 'period_month'], unique=False)
    op.create_index(op.f('ix_payroll_runs_tenant_id'), 'payroll_runs', ['tenant_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.SmallInteger(), nullable=False, comment='1->annual, 2->sick, 3->maternity, 4->unpaid, 5->special'),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.SmallInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='0->pending, 1->approved, 2->rejected, 3->cancelled'),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='chk_leave_requests_dates'),
    sa.CheckConstraint('leave_type BETWEEN 1 AND 5', name='chk_leave_requests_type'),
    sa.CheckConstraint('status IN (0, 1, 2, 3)', name='chk_leave_requests_status'),
    sa.CheckConstraint('total_days > 0', name='chk_leave_requests_days'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leave_requests_employee', 'leave_requests', ['employee_id'], unique=False)
    op.create_index('idx_leave_requests_tenant_status', 'leave_requests', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_tenant_id'), 'leave_requests', ['tenant_id'], unique=False)
    op.create_table('payroll_items',
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('overtime', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bpjs_tk_employee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bpjs_tk_company', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bpjs_kes_employee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bpjs_kes_company', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('pph21', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='0->unpaid, 1->paid'),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('net_salary >= 0', name='chk_payroll_items_net'),
    sa.CheckConstraint('status IN (0, 1)', name='chk_payroll_items_status'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_run_id', 'employee_id', name='uq_payroll_items_run_employee')
    )
    op.create_index('idx_payroll_items_employee', 'payroll_items', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_items_employee_id'), 'payroll_items', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_items_payroll_run_id'), 'payroll_items', ['payroll_run_id'], unique=False)
    op.create_table('reimbursements',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='0->draft, 1->submitted, 2->approved, 3->paid, 4->rejected'),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_reimbursements_amount'),
    sa.CheckConstraint('status IN (0, 1, 2, 3, 4)', name='chk_reimbursements_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reimbursements_employee', 'reimbursements', ['employee_id'], unique=False)
    op.create_index('idx_reimbursements_tenant_status', 'reimbursements', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_reimbursements_employee_id'), 'reimbursements', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reimbursements_tenant_id'), table_name='reimbursements')
    op.drop_index(op.f('ix_reimbursements_employee_id'), table_name='reimbursements')
    op.drop_index('idx_reimbursements_tenant_status', table_name='reimbursements')
    op.drop_index('idx_reimbursements_employee', table_name='reimbursements')
    op.drop_table('reimbursements')
    op.drop_index(op.f('ix_payroll_items_payroll_run_id'), table_name='payroll_items')
    op.drop_index(op.f('ix_payroll_items_employee_id'), table_name='payroll_items')
    op.drop_index('idx_payroll_items_employee', table_name='payroll_items')
    op.drop_table('payroll_items')
    op.drop_index(op.f('ix_leave_requests_tenant_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_index('idx_leave_requests_tenant_status', table_name='leave_requests')
    op.drop_index('idx_leave_requests_employee', table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_payroll_runs_tenant_id'), table_name='payroll_runs')
    op.drop_index('idx_payroll_runs_tenant_period', table_name='payroll_runs')
    op.drop_index('idx_payroll_runs_status', table_name='payroll_runs')
    op.drop_table('payroll_runs')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_designation_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_index('idx_employees_tenant_status', table_name='employees')
    op.drop_index('idx_employees_tenant_dept', table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_designations_tenant_id'), table_name='designations')
    op.drop_index(op.f('ix_designations_department_id'), table_name='designations')
    op.drop_index('idx_designations_tenant_dept', table_name='designations')
    op.drop_table('designations')
    op.drop_index(op.f('ix_departments_tenant_id'), table_name='departments')
    op.drop_index('idx_departments_tenant_status', table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
