"""add_shifts_attendance_fingerprint_documents

Revision ID: c0736cd43d74
Revises: b34900117ba2
Create Date: 2026-09-17 10:53:44.340185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0736cd43d74'
down_revision: Union[str, Sequence[str], None] = 'b34900117ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='1->kontrak_pkwt, 2->sk_pengangkatan, 3->surat_peringatan, 4->surat_tugas, 5->surat_paklaring, 6->surat_mutasi'),
    sa.Column('template_body', sa.Text(), nullable=False, comment='Template markdown/HTML dengan placeholder variabel'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('type BETWEEN 1 AND 6', name='chk_document_templates_type'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_templates_tenant_type', 'document_templates', ['tenant_id', 'type'], unique=False)
    op.create_index(op.f('ix_document_templates_tenant_id'), 'document_templates', ['tenant_id'], unique=False)
    op.create_table('fingerprint_devices',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('device_sn', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='0->offline, 1->online, 2->error'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('status IN (0, 1, 2)', name='chk_fingerprint_devices_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'device_sn', name='uq_fingerprint_devices_sn')
    )
    op.create_index('idx_fingerprint_devices_tenant_status', 'fingerprint_devices', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_fingerprint_devices_tenant_id'), 'fingerprint_devices', ['tenant_id'], unique=False)
    op.create_table('shifts',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_cross_day', sa.Boolean(), nullable=False),
    sa.Column('late_tolerance_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('color_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='0->inactive, 1->active'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('status IN (0, 1)', name='chk_shifts_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_shifts_tenant_code')
    )
    op.create_index('idx_shifts_tenant_status', 'shifts', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_shifts_tenant_id'), 'shifts', ['tenant_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='0->absent, 1->present, 2->late, 3->early_leave, 4->sick, 5->on_leave, 6->holiday'),
    sa.Column('work_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('early_leave_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('source', sa.SmallInteger(), nullable=False, comment='1->fingerprint, 2->mobile_gps, 3->manual_hr, 4->telegram'),
    sa.Column('correction_notes', sa.Text(), nullable=True),
    sa.Column('corrected_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source BETWEEN 1 AND 4', name='chk_attendance_source'),
    sa.CheckConstraint('status BETWEEN 0 AND 6', name='chk_attendance_status'),
    sa.CheckConstraint('work_duration_minutes >= 0 AND late_minutes >= 0 AND overtime_minutes >= 0', name='chk_attendance_durations'),
    sa.ForeignKeyConstraint(['corrected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'employee_id', 'date', name='uq_attendance_tenant_emp_date')
    )
    op.create_index('idx_attendance_emp_date', 'attendance_records', ['employee_id', 'date'], unique=False)
    op.create_index('idx_attendance_tenant_date_status', 'attendance_records', ['tenant_id', 'date', 'status'], unique=False)
    op.create_index(op.f('ix_attendance_records_date'), 'attendance_records', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_shift_id'), 'attendance_records', ['shift_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_tenant_id'), 'attendance_records', ['tenant_id'], unique=False)
    op.create_table('employee_documents',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('letter_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='0->draft, 1->generated, 2->signed, 3->archived'),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('status IN (0, 1, 2, 3)', name='chk_employee_documents_status'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emp_documents_employee', 'employee_documents', ['employee_id'], unique=False)
    op.create_index('idx_emp_documents_tenant_status', 'employee_documents', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_employee_documents_employee_id'), 'employee_documents', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_documents_letter_number'), 'employee_documents', ['letter_number'], unique=False)
    op.create_index(op.f('ix_employee_documents_tenant_id'), 'employee_documents', ['tenant_id'], unique=False)
    op.create_table('fingerprint_employee_mappings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_user_id', sa.String(length=50), nullable=False, comment='PIN pada mesin'),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'device_user_id', name='uq_fp_mappings_tenant_device_uid'),
    sa.UniqueConstraint('tenant_id', 'employee_id', name='uq_fp_mappings_tenant_employee')
    )
    op.create_index(op.f('ix_fingerprint_employee_mappings_employee_id'), 'fingerprint_employee_mappings', ['employee_id'], unique=False)
    op.create_index(op.f('ix_fingerprint_employee_mappings_tenant_id'), 'fingerprint_employee_mappings', ['tenant_id'], unique=False)
    op.create_table('overtime_requests',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='0->pending, 1->approved, 2->rejected'),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='chk_overtime_duration'),
    sa.CheckConstraint('status IN (0, 1, 2)', name='chk_overtime_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_overtime_employee_date', 'overtime_requests', ['employee_id', 'date'], unique=False)
    op.create_index('idx_overtime_tenant_status', 'overtime_requests', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_overtime_requests_employee_id'), 'overtime_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_overtime_requests_tenant_id'), 'overtime_requests', ['tenant_id'], unique=False)
    op.create_table('fingerprint_raw_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('device_user_id', sa.String(length=50), nullable=False, comment='PIN / ID user pada mesin'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verify_mode', sa.SmallInteger(), nullable=False, comment='1->fingerprint, 2->face, 3->rfid, 4->pin'),
    sa.Column('sync_status', sa.SmallInteger(), nullable=False, comment='0->pending, 1->processed, 2->unmatched, 3->duplicate, 4->failed'),
    sa.Column('matched_employee_id', sa.UUID(), nullable=True),
    sa.Column('processed_attendance_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('sync_status IN (0, 1, 2, 3, 4)', name='chk_fingerprint_raw_logs_sync'),
    sa.ForeignKeyConstraint(['device_id'], ['fingerprint_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processed_attendance_id'], ['attendance_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fingerprint_raw_device_time', 'fingerprint_raw_logs', ['device_id', 'timestamp'], unique=False)
    op.create_index('idx_fingerprint_raw_sync', 'fingerprint_raw_logs', ['tenant_id', 'sync_status'], unique=False)
    op.create_index(op.f('ix_fingerprint_raw_logs_device_id'), 'fingerprint_raw_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_fingerprint_raw_logs_device_user_id'), 'fingerprint_raw_logs', ['device_user_id'], unique=False)
    op.create_index(op.f('ix_fingerprint_raw_logs_matched_employee_id'), 'fingerprint_raw_logs', ['matched_employee_id'], unique=False)
    op.create_index(op.f('ix_fingerprint_raw_logs_tenant_id'), 'fingerprint_raw_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_fingerprint_raw_logs_timestamp'), 'fingerprint_raw_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fingerprint_raw_logs_timestamp'), table_name='fingerprint_raw_logs')
    op.drop_index(op.f('ix_fingerprint_raw_logs_tenant_id'), table_name='fingerprint_raw_logs')
    op.drop_index(op.f('ix_fingerprint_raw_logs_matched_employee_id'), table_name='fingerprint_raw_logs')
    op.drop_index(op.f('ix_fingerprint_raw_logs_device_user_id'), table_name='fingerprint_raw_logs')
    op.drop_index(op.f('ix_fingerprint_raw_logs_device_id'), table_name='fingerprint_raw_logs')
    op.drop_index('idx_fingerprint_raw_sync', table_name='fingerprint_raw_logs')
    op.drop_index('idx_fingerprint_raw_device_time', table_name='fingerprint_raw_logs')
    op.drop_table('fingerprint_raw_logs')
    op.drop_index(op.f('ix_overtime_requests_tenant_id'), table_name='overtime_requests')
    op.drop_index(op.f('ix_overtime_requests_employee_id'), table_name='overtime_requests')
    op.drop_index('idx_overtime_tenant_status', table_name='overtime_requests')
    op.drop_index('idx_overtime_employee_date', table_name='overtime_requests')
    op.drop_table('overtime_requests')
    op.drop_index(op.f('ix_fingerprint_employee_mappings_tenant_id'), table_name='fingerprint_employee_mappings')
    op.drop_index(op.f('ix_fingerprint_employee_mappings_employee_id'), table_name='fingerprint_employee_mappings')
    op.drop_table('fingerprint_employee_mappings')
    op.drop_index(op.f('ix_employee_documents_tenant_id'), table_name='employee_documents')
    op.drop_index(op.f('ix_employee_documents_letter_number'), table_name='employee_documents')
    op.drop_index(op.f('ix_employee_documents_employee_id'), table_name='employee_documents')
    op.drop_index('idx_emp_documents_tenant_status', table_name='employee_documents')
    op.drop_index('idx_emp_documents_employee', table_name='employee_documents')
    op.drop_table('employee_documents')
    op.drop_index(op.f('ix_attendance_records_tenant_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_shift_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_date'), table_name='attendance_records')
    op.drop_index('idx_attendance_tenant_date_status', table_name='attendance_records')
    op.drop_index('idx_attendance_emp_date', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_shifts_tenant_id'), table_name='shifts')
    op.drop_index('idx_shifts_tenant_status', table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_fingerprint_devices_tenant_id'), table_name='fingerprint_devices')
    op.drop_index('idx_fingerprint_devices_tenant_status', table_name='fingerprint_devices')
    op.drop_table('fingerprint_devices')
    op.drop_index(op.f('ix_document_templates_tenant_id'), table_name='document_templates')
    op.drop_index('idx_doc_templates_tenant_type', table_name='document_templates')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
